services:
  datascience:
    image: gnasello/image-analysis-env:2026-08-19.2
    container_name: image-analysis-env
    user: root
    ports:
      - 8888:8888
    environment:
    #- NB_UID={NB_UID}
    #- NB_GID={NB_GID}
    - CHOWN_HOME=yes
    - CHOWN_HOME_OPTS=-R
    - GRANT_SUDO=yes
    #- JUPYTER_PORT=8888