channels:
  - conda-forge
dependencies:
  - jupyter-server-proxy>=4.3.0
  - jupyterhub-singleuser
  - pip
  - napari
  - pyside6      # This installs the stable, official Qt6 framework
  - openjdk=11 
  - maven 
  - pyimagej
  - bioio
  - pip
  - pip:
      - bioio-ome-tiff
